---
- hosts: deploy
  become: yes
  user: devopsvm
  vars:
  - warName: tudu.war
  - warRemotePath: /etc/ansible/
  tasks:
  - name: deploy WAR file
    copy: src={{ warRemotePath }}/{{ warName }} dest=/opt/tomcat7/apache-tomcat-7.0.75/webapps  mode=0755
  notify:
  - restart tomcat7

