---
- hosts: tomcatserver
  become_method: sudo
  vars:
  - warName: tudu*
  - warRemotePath: /etc/ansible

  tasks:
  - name: copying WAR file
    copy:  src=/etc/ansible/tudu*  dest=/opt/tomcat7/apache-tomcat-7.0.75/webapps/
